### ISSUE TITLE
Logging error when channel has uppercase characters

### ISSUE THREAD

**Issue by jonathanmtran** [villelahdenvuo/tuhBot#3]
When a channel folder contains an uppercase letter, the user would get a similar error
`Error: ENOENT, open '/home/jtran/tuhBot/irc/IRCNet/#tuhtest/channel.log'`

This happens when the channel is capitalized as #tuhTest

**Comment by villelahdenvuo** [comment]
Currently it only supports lowercase channel names, but that's not really a problem because channel names are case-insensitive, just rename the folder to #tuhtest and it should work. But yeah, I acknowledge this problem.
